name: kairat
description: "FC Kairat app"
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  go_router: ^14.4.1
  flutter_bloc: ^8.1.6
  flutter_native_splash: ^2.4.2
  flutter_svg: ^2.0.14
  dio: ^5.7.0
  shared_preferences: ^2.3.3
  equatable: ^2.0.7
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/icons/
    - assets/sounds/

  fonts:
    - family: Proxima Nova
      fonts:
        - asset: fonts/proxima_nova/proxima-nova-black.ttf
          weight: 900
        - asset: fonts/proxima_nova/proxima-nova-bold.ttf
          weight: 700
        - asset: fonts/proxima_nova/proxima-nova-semibold.ttf
          weight: 600
        - asset: fonts/proxima_nova/proxima-nova-regular.ttf
          weight: 400
        - asset: fonts/proxima_nova/proxima-nova-light.ttf
          weight: 300
        - asset: fonts/proxima_nova/proxima-nova-thin.ttf
          weight: 100

flutter_native_splash:
  color: "#000000"
  image: "assets/images/splash.png"
  android: true
  ios: true
# dart run flutter_native_splash:create
